# -*- coding: utf-8 -*-
"""IcNumberGender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V62Xf0QuZpfVQRoV07uArz4E59cnvrEE
"""



# import library
from google.colab import files
import pandas as pd
import numpy as np

# upload file into google colab
upload_file = files.upload()
file = next(iter(upload_file))

# read file
df = pd.read_excel(file)

# rules
# if National id last digit is even / 0 , gender = female
# if National id last digit is odd , gender = male

# using np.where method instead of for loop to simplify code
# to avoid converting National id to integer and lose leading zero in national id
# I convert only the last digit
df['Gender'] = np.where(
    (df['National ID'].str[-1].astype(int) % 2 == 0) |
    (df['National ID'].str[-1] == '0') ,
    'Female',
    'Male'
  )

# Adding 'Updated' to old file name
current_filename = file[:-5]
output_file = f'Updated {current_filename}.xlsx'

# save to excel and download
df.to_excel(output_file, index = False)
files.download(output_file)

