# -*- coding: utf-8 -*-
"""IcNumberProcessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iPHGXoUTFhcIJYHkc_GgLHhZ23RE_x2H
"""

# import library
from google.colab import files
import pandas as pd
import datetime

# upload file into google colab
uploaded_file = files.upload()
file_name = next(iter(uploaded_file))

# function to calculate birthdate
def calculate_birtdate(national_id):
  year = national_id[0:2]
  month = national_id[2:4]
  day = national_id[4:6]

  current_year = datetime.datetime.now().year % 100

  # determine the century based on last 2 digit in year
  if int(year) <= current_year:
    century = 20
  else:
    century = 19

  # combine year,month and day into dd/mm/yyyy format
  birthdate = f"{day}/{month}/{century}{year}"

  return birthdate

# function to calculate age
def calculate_age(birthdate):
  current_year = datetime.datetime.now().year
  birth_year = int(birthdate[-4:])
  age = current_year - birth_year

  return age

# manipulate file
df = pd.read_excel(file_name)

national_ids = df['National ID']
birthdates = df['Birthdate']
ages = df['Age']

# iterate over national id column and fill birthdate and age column
for i, national_id in enumerate(national_ids):
  if len(national_id) == 14:
    birthdate = calculate_birtdate(national_id)
    age = calculate_age(birthdate)
    df.at[i, 'Birthdate'] = birthdate
    df.at[i, 'Age'] = age

# save changes and download file
output_file = 'Result for masterfile.xlsx'
df.to_excel(output_file, index = False)
files.download(output_file)