# -*- coding: utf-8 -*-
"""icnumberprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DGGgBMEZeKwf3UFByxUzji5Jl-fyqTC
"""

# import library
from google.colab import files
import pandas as pd
import datetime

# upload file into google colab
uploaded_file = files.upload()
file = next(iter(uploaded_file))

# function to calculate birthdate
def calculate_birthdate(national_id):
  year = national_id[0:2]
  month = national_id[2:4]
  day = national_id[4:6]

  current_year = datetime.datetime.now().year % 100

  # determine the century based on last 2 digit in year
  if int(year) <= current_year:
    century = 20
  else:
    century = 19

  # combine year,month and day into dd/mm/yyyy format
  birthdate = f"{day}/{month}/{century}{year}"

  return birthdate

# function to calculate age
def calculate_age(birthdate):
  current_year = datetime.datetime.now().year
  birth_year = int(birthdate[-4:])
  age = current_year - birth_year

  return age

# manipulate file
df = pd.read_excel(file)
filter_df = df[
      (df['National ID'].astype(str).str.len() == 14) &
      df['National ID'].notna() &
      (df['National ID'] != '')
      ].copy()

filter_df['Birthdate'] = filter_df['National ID'].apply(calculate_birthdate)
filter_df['Age'] = filter_df['Birthdate'].apply(calculate_age)

df.loc[filter_df.index, ['Birthdate', 'Age']] = filter_df[['Birthdate', 'Age']]

# rename file with new name
current_filename = file[:-5]
output_file = f'Updated {current_filename}.xlsx'

# save to excel and download
df.to_excel(output_file, index = False)
files.download(output_file)